export type DemoVendor = {
  uid: string
  name: string
  location?: string
  specialty?: string[]
  rating?: number
  reviewCount?: number
  badge?: string
  description?: string
  contactEmail?: string
  platforms?: string[]
  minOrder?: number
  topBrands?: string[]
}

export type DemoProduct = {
  id: string
  vendorUid: string
  vendorName: string
  name: string
  brand: string
  model?: string
  size?: string
  price: number
  retailPrice?: number
  condition?: 'New' | 'Used' | 'DS'
  image?: string
  images?: string[]
  platform?: string
  colorway?: string
  sku?: string
  soldCount?: number
  description?: string
  active?: boolean
  status?: string
}

export const demoVendors: DemoVendor[] = [
  {
    uid: '__demo__kickvault',
    name: 'KickVault',
    location: 'Atlanta, GA',
    specialty: ['Jordan', 'Nike SB'],
    rating: 4.9,
    reviewCount: 312,
    badge: 'Top Seller',
    description:
      'One of the most trusted Jordan resellers in the southeast. KickVault specializes in OG colorways, grails, and limited drops. All shoes authenticated before listing.',
    contactEmail: 'kickvault@soletrack.com',
    platforms: ['StockX', 'GOAT', 'eBay'],
    minOrder: 1,
    topBrands: ['Jordan', 'Nike'],
  },
  {
    uid: '__demo__solesource',
    name: 'SoleSource',
    location: 'Los Angeles, CA',
    specialty: ['Nike', 'Adidas'],
    rating: 4.7,
    reviewCount: 198,
    badge: 'Verified',
    description:
      'West Coast sneaker connect. Consistent supply of Dunks, Air Force 1s, and Yeezy drops. Ships same day on all confirmed orders.',
    contactEmail: 'solesource@soletrack.com',
    platforms: ['GOAT', 'Local', 'Instagram'],
    minOrder: 2,
    topBrands: ['Nike', 'Adidas'],
  },
  {
    uid: '__demo__yzydealer',
    name: 'YZYDealer',
    location: 'Chicago, IL',
    specialty: ['Adidas', 'Yeezy'],
    rating: 4.8,
    reviewCount: 441,
    badge: 'Top Seller',
    description:
      'The go-to source for Yeezy supply. Every colorway since 2018, in most sizes. Bulk deals available for flippers. No fakes — every pair verified.',
    contactEmail: 'yzydealer@soletrack.com',
    platforms: ['StockX', 'eBay'],
    minOrder: 1,
    topBrands: ['Adidas'],
  },
  {
    uid: '__demo__retroracks',
    name: 'RetroRacks',
    location: 'New York, NY',
    specialty: ['Jordan', 'Nike Retro'],
    rating: 4.6,
    reviewCount: 127,
    badge: 'Verified',
    description:
      'Specializing in retro Jordan 3s, 4s, and 5s. RetroRacks keeps inventory lean and quality high. Great source for resellers focused on classic silhouettes.',
    contactEmail: 'retrorack@soletrack.com',
    platforms: ['eBay', 'StockX', 'Local'],
    minOrder: 1,
    topBrands: ['Jordan'],
  },
  {
    uid: '__demo__cactuskicks',
    name: 'CactusKicks',
    location: 'Houston, TX',
    specialty: ['Travis Scott Collab', 'Nike SB'],
    rating: 5.0,
    reviewCount: 76,
    badge: 'New',
    description:
      'Boutique vendor specializing in high-heat collabs. Travis Scott, Off-White, and other designer collaborations. Limited supply, serious buyers only.',
    contactEmail: 'cactuskicks@soletrack.com',
    platforms: ['StockX', 'GOAT'],
    minOrder: 1,
    topBrands: ['Nike', 'Jordan'],
  },
  {
    uid: '__demo__nbvault',
    name: 'NB Vault',
    location: 'Boston, MA',
    specialty: ['New Balance', 'Saucony'],
    rating: 4.5,
    reviewCount: 89,
    badge: 'Verified',
    description:
      'The best NB connect in New England. Stocking 550s, 990s, 993s, and more. Also carries limited Saucony drops. Wholesale pricing for bulk buyers.',
    contactEmail: 'nbvault@soletrack.com',
    platforms: ['GOAT', 'Local'],
    minOrder: 3,
    topBrands: ['New Balance', 'Saucony'],
  },
]

export const demoProducts: DemoProduct[] = [
  {
    id: 'demo-1',
    name: 'Air Jordan 1 Retro High OG',
    brand: 'Jordan',
    size: '10',
    price: 289,
    retailPrice: 180,
    condition: 'DS',
    image: '/images/shoes/pexels-dl-jordan-11718014.jpg',
    platform: 'StockX',
    colorway: 'Chicago / Red Black',
    sku: '555088-101',
    vendorUid: '__demo__kickvault',
    vendorName: 'KickVault',
    soldCount: 142,
    description: 'The iconic AJ1 High OG in classic colorway. Deadstock, never worn. Original box included with all accessories.',
  },
  {
    id: 'demo-2',
    name: 'Nike Dunk Low Retro',
    brand: 'Nike',
    size: '9.5',
    price: 145,
    retailPrice: 110,
    condition: 'New',
    image: '/images/shoes/pexels-dl-nike-dunk-20298285.jpg',
    platform: 'GOAT',
    colorway: 'White / Black Panda',
    sku: 'DD1391-100',
    vendorUid: '__demo__solesource',
    vendorName: 'SoleSource',
    soldCount: 87,
    description: 'Clean Panda Dunk Low. Tried on once indoors. No creases, no dirt. Box slightly dented.',
  },
  {
    id: 'demo-3',
    name: 'Adidas Yeezy Boost 350 V2',
    brand: 'Adidas',
    size: '11',
    price: 320,
    retailPrice: 230,
    condition: 'DS',
    image: '/images/shoes/pexels-dl-yeezy-1461048.jpg',
    platform: 'StockX',
    colorway: 'Zebra',
    sku: 'CP9654',
    vendorUid: '__demo__yzydealer',
    vendorName: 'YZYDealer',
    soldCount: 205,
    description: 'Zebra 350 V2 — one of the most sought-after Yeezy colorways. Deadstock with original receipt.',
  },
  {
    id: 'demo-4',
    name: 'Jordan 4 Retro Military Blue',
    brand: 'Jordan',
    size: '10.5',
    price: 410,
    retailPrice: 210,
    condition: 'DS',
    image: '/images/shoes/pexels-dl-jordan-10853637.jpg',
    platform: 'eBay',
    colorway: 'Military Blue',
    sku: 'DH6927-111',
    vendorUid: '__demo__retroracks',
    vendorName: 'RetroRacks',
    soldCount: 63,
    description: 'Clean Military Blue 4 — DS with box and extra laces.',
  },
  {
    id: 'demo-5',
    name: 'Nike Air Max 90',
    brand: 'Nike',
    size: '9',
    price: 110,
    retailPrice: 130,
    condition: 'Used',
    image: '/images/shoes/pexels-dl-sneaker-26775750.jpg',
    platform: 'Local',
    colorway: 'Infrared',
    sku: 'CT1685-100',
    vendorUid: '__demo__solesource',
    vendorName: 'SoleSource',
    soldCount: 31,
    description: 'Light use, still clean. Minor sole yellowing. Great daily beater.',
  },
  {
    id: 'demo-6',
    name: 'New Balance 550 White Green',
    brand: 'New Balance',
    size: '10',
    price: 130,
    retailPrice: 110,
    condition: 'New',
    image: '/images/shoes/pexels-dl-nb-19882433.jpg',
    platform: 'GOAT',
    colorway: 'White / Green',
    sku: 'BB550WT1',
    vendorUid: '__demo__nbvault',
    vendorName: 'NB Vault',
    soldCount: 54,
    description: 'Crispy 550 colorway. Brand new, never worn. Original box and paper.',
  },
  {
    id: 'demo-7',
    name: 'Air Jordan 3 Retro Fire Red',
    brand: 'Jordan',
    size: '11',
    price: 375,
    retailPrice: 200,
    condition: 'DS',
    image: '/images/shoes/pexels-dl-jordan-11281577.jpg',
    platform: 'StockX',
    colorway: 'Fire Red',
    sku: 'CT8532-160',
    vendorUid: '__demo__kickvault',
    vendorName: 'KickVault',
    soldCount: 98,
    description: 'Fire Red 3 — elephant print sharp, DS with box.',
  },
  {
    id: 'demo-8',
    name: 'Nike SB Dunk Low (Special Release)',
    brand: 'Nike',
    size: '10',
    price: 850,
    retailPrice: 150,
    condition: 'DS',
    image: '/images/shoes/pexels-dl-nike-dunk-20298289.jpg',
    platform: 'StockX',
    colorway: 'Brown / Sail',
    sku: 'CT5053-200',
    vendorUid: '__demo__cactuskicks',
    vendorName: 'CactusKicks',
    soldCount: 19,
    description: 'Limited SB release. DS, never worn. Ships double boxed.',
  },
  {
    id: 'demo-9',
    name: 'Adidas Forum Low x Bad Bunny',
    brand: 'Adidas',
    size: '9',
    price: 290,
    retailPrice: 160,
    condition: 'New',
    image: '/images/shoes/pexels-dl-yeezy-2364579.jpg',
    platform: 'GOAT',
    colorway: 'Easter Egg',
    sku: 'GW0265',
    vendorUid: '__demo__solesource',
    vendorName: 'SoleSource',
    soldCount: 44,
    description: 'Bad Bunny x Forum Low in the Easter Egg colorway. Tried on once for photos. Pristine condition.',
  },
  {
    id: 'demo-10',
    name: 'Nike Air Force 1 Low White',
    brand: 'Nike',
    size: '10',
    price: 95,
    retailPrice: 110,
    condition: 'New',
    image: '/images/shoes/sneaker-af1-white.webp',
    platform: 'Local',
    colorway: 'Triple White',
    sku: 'CW2288-111',
    vendorUid: '__demo__solesource',
    vendorName: 'SoleSource',
    soldCount: 210,
    description: 'Classic triple white AF1. Brand new in box. Clean, versatile, goes with everything.',
  },
  {
    id: 'demo-11',
    name: 'Jordan 6 Retro Carmine',
    brand: 'Jordan',
    size: '9.5',
    price: 230,
    retailPrice: 190,
    condition: 'DS',
    image: '/images/shoes/sneaker-jordan6-carmine.webp',
    platform: 'StockX',
    colorway: 'Carmine',
    sku: 'CT8529-106',
    vendorUid: '__demo__retroracks',
    vendorName: 'RetroRacks',
    soldCount: 77,
    description: 'Jordan 6 Carmine — clean retro of the OG MJ colorway. DS with box.',
  },
  {
    id: 'demo-12',
    name: 'New Balance 990v5 Grey',
    brand: 'New Balance',
    size: '11',
    price: 185,
    retailPrice: 185,
    condition: 'New',
    image: '/images/shoes/sneaker-nb990-grey.webp',
    platform: 'GOAT',
    colorway: 'Grey / White',
    sku: 'M990GL5',
    vendorUid: '__demo__nbvault',
    vendorName: 'NB Vault',
    soldCount: 36,
    description: 'Made in USA 990v5. Premium build quality, perfect everyday runner.',
  },
  {
    id: 'demo-13',
    name: 'Nike Blazer Mid 77 Vintage',
    brand: 'Nike',
    size: '9',
    price: 88,
    retailPrice: 100,
    condition: 'New',
    image: '/images/shoes/sneaker-blazer-mid.webp',
    platform: 'Local',
    colorway: 'White / Black',
    sku: 'CI1172-100',
    vendorUid: '__demo__solesource',
    vendorName: 'SoleSource',
    soldCount: 65,
    description: 'Vintage-look Blazer Mid 77. Worn once. No creasing, clean toe box.',
  },
  {
    id: 'demo-14',
    name: 'Adidas Ultra Boost 22',
    brand: 'Adidas',
    size: '10.5',
    price: 140,
    retailPrice: 190,
    condition: 'Used',
    image: '/images/shoes/sneaker-ultraboost-black.webp',
    platform: 'eBay',
    colorway: 'Core Black',
    sku: 'GX5591',
    vendorUid: '__demo__yzydealer',
    vendorName: 'YZYDealer',
    soldCount: 22,
    description: 'Ultra Boost 22 in core black. Light wear, responsive boost cushion still perfect.',
  },
  {
    id: 'demo-15',
    name: 'Jordan 1 Mid Chicago Black Toe',
    brand: 'Jordan',
    size: '10',
    price: 165,
    retailPrice: 115,
    condition: 'DS',
    image: '/images/shoes/sneaker-jordan1-mid.webp',
    platform: 'GOAT',
    colorway: 'Black / Red / White',
    sku: '554724-069',
    vendorUid: '__demo__kickvault',
    vendorName: 'KickVault',
    soldCount: 118,
    description: 'AJ1 Mid in the Chicago Black Toe colorway. Clean, DS, box included.',
  },
  // ── Market scenario demos — prices relative to brandStats.json averages (~$121) ──
  // demo-market-a: Nike @ $124 → +2.5% above avg → "At market" / Fair bucket
  {
    id: 'demo-market-a',
    name: 'Nike Air Force 1 Mid Essential',
    brand: 'Nike',
    size: '10',
    price: 124,
    retailPrice: 120,
    condition: 'New',
    image: '/images/shoes/pexels-dl-af1-11281577.jpg',
    platform: 'Local',
    colorway: 'White / White',
    sku: 'DH7579-100',
    vendorUid: '__demo__solesource',
    vendorName: 'SoleSource',
    soldCount: 183,
    description: 'Classic mid-cut AF1 in clean all-white. Brand new in box. Priced right at market.',
  },
  // demo-market-b: Puma @ $98 → -19% below avg → price--great-deal
  {
    id: 'demo-market-b',
    name: 'Puma Suede Classic XXI',
    brand: 'Puma',
    size: '10.5',
    price: 98,
    retailPrice: 110,
    condition: 'New',
    image: '/images/shoes/sneaker-puma-suede.webp',
    platform: 'Local',
    colorway: 'Peacoat / White',
    sku: '374915-07',
    vendorUid: '__demo__solesource',
    vendorName: 'SoleSource',
    soldCount: 47,
    description: 'Iconic Puma Suede in navy. Brand new, below market. Moving inventory fast.',
  },
  // demo-market-c: ASICS @ $149 → +23% above avg → price--high / High Risk bucket
  {
    id: 'demo-market-c',
    name: 'ASICS Gel-Kayano 14 Cream',
    brand: 'Asics',
    size: '9.5',
    price: 149,
    retailPrice: 100,
    condition: 'DS',
    image: '/images/shoes/sneaker-asics-kayano.webp',
    platform: 'StockX',
    colorway: 'Cream / Sage',
    sku: '1201A019-107',
    vendorUid: '__demo__retroracks',
    vendorName: 'RetroRacks',
    soldCount: 12,
    description: 'GK14 in the trending cream colorway. DS, shipped in original box. Priced at ask.',
  },
  // demo-market-d: Reebok @ $108 → -10% below avg → price--deal
  {
    id: 'demo-market-d',
    name: 'Reebok Classic Leather Legacy',
    brand: 'Reebok',
    size: '10',
    price: 108,
    retailPrice: 90,
    condition: 'New',
    image: '/images/shoes/sneaker-reebok-classic.webp',
    platform: 'eBay',
    colorway: 'White / Chalk',
    sku: 'GY7158',
    vendorUid: '__demo__nbvault',
    vendorName: 'NB Vault',
    soldCount: 29,
    description: 'Clean Reebok Classic in white chalk. New in box, slightly below market average.',
  },
]

export function demoVendorByUid(uid: string) {
  return demoVendors.find((v) => v.uid === uid) ?? null
}

export function demoProductsForVendor(uid: string) {
  return demoProducts.filter((p) => p.vendorUid === uid)
}
